"""Live accompaniment primitives for Rubato."""

from aimusic.accompaniment.bundle_v2 import (
    BundleLoaderV2,
    BundleManifest,
    BundleReadiness,
    BundleRef,
    BundleRegistry,
    CanonicalTimeline,
    ScorePosition,
    ScoreSpan,
    SourceMappingDocument,
    SourceRole,
    TimelineDocument,
)
from aimusic.accompaniment.closed_loop_evaluation import (
    AggregateOnsetMetric,
    BeatOnsetMetric,
    ClosedLoopEvaluationConfig,
    ClosedLoopEvaluationReport,
    DeliveredEventMetric,
    LandmarkOnsetMetric,
    SoloTimingPoint,
    evaluate_closed_loop,
    evaluate_projection_closed_loop,
    load_aligned_midi_take,
    write_closed_loop_report,
)
from aimusic.accompaniment.evaluation import ScheduleEvaluation, evaluate_scheduled_events
from aimusic.accompaniment.following import (
    FollowerUpdate,
    OracleFollower,
    PerformedNote,
    ReferencePitchFollower,
    ScoreFollower,
)
from aimusic.accompaniment.live_engine import LiveEngine
from aimusic.accompaniment.matchmaker_follower import (
    MatchmakerMidiRun,
    MatchmakerStreamFollower,
    run_matchmaker_midi_file,
)
from aimusic.accompaniment.midi_output import MidoAccompanimentOutput
from aimusic.accompaniment.runtime_contracts import (
    LiveStateWord,
    RunMode,
    RunPhase,
    RuntimeConfig,
    RuntimeStatus,
)
from aimusic.accompaniment.runtime_io import (
    CapturingOutput,
    JsonlTraceSink,
    ManualClock,
    RecordedNoteReplay,
    SystemMonotonicClock,
)
from aimusic.accompaniment.runtime_projection import (
    MOVEMENT_2_BUNDLE_ID,
    ProvisionalRuntimeProjection,
    default_bundle_registry,
    project_bundle_v2_to_provisional_runtime,
)
from aimusic.accompaniment.scheduler import (
    AccompanimentOutput,
    AccompanimentScheduler,
    ArrivalTimeCurve,
    CurveEventTiming,
    FlatScoreArrivalCurve,
    ReferenceWarpArrivalCurve,
    ScheduledAccompanimentEvent,
    SchedulerUpdate,
)
from aimusic.accompaniment.score_bundle import (
    InstrumentMapEntry,
    LegacyScoreBundleAdapter,
    ScoreBundle,
    ScoreBundleMetadata,
    ScoreEvent,
    ScorePart,
)
from aimusic.accompaniment.section_policy import (
    AccompanimentMode,
    Section,
    SectionMap,
)
from aimusic.accompaniment.simulation import (
    SimulationTrace,
    generate_synthetic_performance,
    hide_score_beats,
    run_simulated_online,
)
from aimusic.accompaniment.tempo_model import OnlineTempoModel, TempoState

__all__ = [
    "AccompanimentMode",
    "AccompanimentOutput",
    "AccompanimentScheduler",
    "ArrivalTimeCurve",
    "AggregateOnsetMetric",
    "BeatOnsetMetric",
    "BundleLoaderV2",
    "BundleManifest",
    "BundleReadiness",
    "BundleRef",
    "BundleRegistry",
    "CanonicalTimeline",
    "CapturingOutput",
    "ClosedLoopEvaluationConfig",
    "ClosedLoopEvaluationReport",
    "CurveEventTiming",
    "DeliveredEventMetric",
    "FlatScoreArrivalCurve",
    "FollowerUpdate",
    "InstrumentMapEntry",
    "JsonlTraceSink",
    "LegacyScoreBundleAdapter",
    "LiveEngine",
    "LiveStateWord",
    "LandmarkOnsetMetric",
    "MatchmakerMidiRun",
    "MatchmakerStreamFollower",
    "ManualClock",
    "MidoAccompanimentOutput",
    "MOVEMENT_2_BUNDLE_ID",
    "OnlineTempoModel",
    "OracleFollower",
    "PerformedNote",
    "ProvisionalRuntimeProjection",
    "ReferencePitchFollower",
    "ReferenceWarpArrivalCurve",
    "RecordedNoteReplay",
    "RunMode",
    "RunPhase",
    "RuntimeConfig",
    "RuntimeStatus",
    "ScheduleEvaluation",
    "ScoreBundle",
    "ScoreBundleMetadata",
    "ScoreEvent",
    "ScoreFollower",
    "ScorePart",
    "ScorePosition",
    "ScoreSpan",
    "Section",
    "SectionMap",
    "SchedulerUpdate",
    "ScheduledAccompanimentEvent",
    "SimulationTrace",
    "SourceMappingDocument",
    "SourceRole",
    "SoloTimingPoint",
    "TempoState",
    "TimelineDocument",
    "SystemMonotonicClock",
    "generate_synthetic_performance",
    "default_bundle_registry",
    "hide_score_beats",
    "evaluate_scheduled_events",
    "evaluate_closed_loop",
    "evaluate_projection_closed_loop",
    "load_aligned_midi_take",
    "run_matchmaker_midi_file",
    "project_bundle_v2_to_provisional_runtime",
    "run_simulated_online",
    "write_closed_loop_report",
]
